def palabra():
    nombre=raw_input("NOMBRE: ")
    apellido=raw_input("APELLIDO: ")
    print("Buenos dias, "+nombre+" "+apellido)
    print("Tu lindo nombre empieza por la letra "+nombre[0])
    print("Voy a deletrear tu nombre")
    print(nombre[0])
    print(nombre[1])
    print(nombre[2])
    print(nombre[3])
palabra()
